categories:
- Data Managers
description: Index a FASTA file for use with NOVO-ALIGN and populate the novo_index.nix file.
long_description: ''
name: data_manager_novoalign_index_builder
owner: sanbi-uwc
remote_repository_url: https://github.com/zipho/data_manager_novoalign_index_builder
type: unrestricted
